language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - pypy

install:
  - pip install nose coverage coveralls .
script:
  - nosetests
after_success:
  - mkdir -p build/lib
  - coverage run --source=permutation.py setup.py -q test
  - coveralls
